// <auto-generated />
using System;
using EFCoreTutoral.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreTutoral.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    partial class EfCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreTutoral.Models.AddressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("AddressTBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "123 Main st",
                            Address2 = "Apt 5",
                            City = "NewCity",
                            State = "Ohio",
                            ZipCode = "43224"
                        },
                        new
                        {
                            Id = 2,
                            Address1 = "123 Addres 2",
                            Address2 = "Apt 5",
                            City = "NewCity",
                            State = "Ohio",
                            ZipCode = "43224"
                        });
                });

            modelBuilder.Entity("EFCoreTutoral.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<int?>("BillingAddressID")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddressID");

                    b.HasIndex("BillingAddressID");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("UserTBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressID = 1,
                            BillingAddressID = 2,
                            EmailAddress = "John@noWay.com",
                            FirstName = "John",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("EFCoreTutoral.Models.UserModel", b =>
                {
                    b.HasOne("EFCoreTutoral.Models.AddressModel", "AddressModel")
                        .WithMany()
                        .HasForeignKey("AddressID");

                    b.HasOne("EFCoreTutoral.Models.AddressModel", "BillAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressID");

                    b.Navigation("AddressModel");

                    b.Navigation("BillAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
